In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [2]:
song_df = pd.read_csv(r'C:\Users\paawan\Desktop\project\data\278k_song_labelled.csv')

In [3]:
song_df.head()

Unnamed: 0  duration (ms)  danceability  energy  loudness  speechiness  \
0           0         195000         0.611   0.614    -8.815       0.0672   
1           1         194641         0.638   0.781    -6.848       0.0285   
2           2         217573         0.560   0.810    -8.029       0.0872   
3           3         443478         0.525   0.699    -4.571       0.0353   
4           4         225862         0.367   0.771    -5.863       0.1060   

   acousticness  instrumentalness  liveness  valence    tempo     spec_rate  \
0        0.0169          0.000794    0.7530    0.520  128.050  3.450000e-07   
1        0.0118          0.009530    0.3490    0.250  122.985  1.460000e-07   
2        0.0071          0.000008    0.2410    0.247  170.044  4.010000e-07   
3        0.0178          0.000088    0.0888    0.199   92.011  7.960000e-08   
4        0.3650          0.000001    0.0965    0.163  115.917  4.690000e-07   

   labels  
0       2  
1       1  
2       1  
3       0  
4       1

In [4]:
imp_data = song_df.drop(['Unnamed: 0','duration (ms)', 'instrumentalness','spec_rate','speechiness','loudness','valence'],axis = 1)

In [5]:
imp_data.head()

danceability  energy  acousticness  liveness    tempo  labels
0         0.611   0.614        0.0169    0.7530  128.050       2
1         0.638   0.781        0.0118    0.3490  122.985       1
2         0.560   0.810        0.0071    0.2410  170.044       1
3         0.525   0.699        0.0178    0.0888   92.011       0
4         0.367   0.771        0.3650    0.0965  115.917       1

In [6]:
x = imp_data.iloc[:,:-1]
y = imp_data.iloc[:,-1]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [9]:
model = LogisticRegression()

In [10]:
model.fit(x_train,y_train)

c:\Users\paawan\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [11]:
y_pred = model.predict(x_test)

In [12]:
classification_report(y_pred,y_test)

'              precision    recall  f1-score   support\n\n           0       0.65      0.67      0.66     15794\n           1       0.83      0.77      0.80     23085\n           2       0.76      0.77      0.76      9348\n           3       0.60      0.69      0.64      7361\n\n    accuracy                           0.73     55588\n   macro avg       0.71      0.72      0.72     55588\nweighted avg       0.74      0.73      0.73     55588\n'

In [13]:
(accuracy_score(y_pred,y_test)*100).round(3)

73.133

In [14]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
knn_model = KNeighborsClassifier(n_neighbors= 4)


In [16]:
knn_model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [17]:
y_pred_knn = knn_model.predict(x_test)

In [18]:
(accuracy_score(y_pred_knn,y_pred)*100).round(3)

77.918

In [19]:
import pickle

In [20]:
pickle.dump(knn_model,open('knn_model.pkl','wb'))

In [21]:
pickle.dump(model,open('lr_model.pkl','wb'))

In [22]:
x_train.head()

danceability  energy  acousticness  liveness    tempo
262233         0.456   0.438      0.119000    0.4940  152.964
111667         0.719   0.560      0.121000    0.0499   79.001
7850           0.919   0.392      0.000694    0.1080  144.021
214058         0.136   0.101      0.941000    0.0773  143.014
150187         0.522   0.864      0.012300    0.2910  174.001

In [23]:
x_test.head()

danceability  energy  acousticness  liveness    tempo
27860          0.267   0.127       0.96100     0.137   78.303
164271         0.250   0.922       0.03480     0.175   78.011
223548         0.394   0.416       0.02570     0.100  119.940
271107         0.629   0.528       0.55200     0.114   83.306
251348         0.314   0.983       0.00014     0.282  184.084

In [24]:
y_test

27860     3
164271    2
223548    3
271107    0
251348    2
         ..
161964    0
223107    1
213791    1
210651    0
41155     0
Name: labels, Length: 55588, dtype: int64

In [25]:
myarr = np.array([0.1,0.6,1.2,0.5,111.2])
myarr.reshape(1,5)


array([[1.000e-01, 6.000e-01, 1.200e+00, 5.000e-01, 1.112e+02]])

In [26]:
x_test.shape

(55588, 5)

In [27]:
df = pd.DataFrame([myarr],columns=['danceability','energy','acousticness','liveness','tempo'])

In [28]:
df

danceability  energy  acousticness  liveness  tempo
0           0.1     0.6           1.2       0.5  111.2

In [29]:
model.predict(df)

array([3], dtype=int64)

In [30]:
feature = np.array([1,2,3,4,5])

In [31]:
feature.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [32]:
feature

array([1, 2, 3, 4, 5])

In [33]:
y_pred.shape

(55588,)

In [34]:
feature = np.array([0.1, 0.2, 0.4, 0.4, 0.005])
feature.reshape(1,5)
features = pd.DataFrame([feature],columns = ['danceability','energy','acousticness','liveness','tempo'])
prediction = model.predict(features)
prediction = prediction[0]

In [36]:
type(prediction)

numpy.int64

In [39]:
mydict = {0:'Sad',1:'Happy',2:'Energetic',3:'Calm'}
mydict[prediction]

'Sad'

In [40]:
if prediction in mydict:
    print("x")

x
