In [59]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [60]:
song_df = pd.read_csv(r'C:\Users\paawan\Desktop\project\data\278k_song_labelled.csv')

In [61]:
song_df.head()

Unnamed: 0  duration (ms)  danceability  energy  loudness  speechiness  \
0           0         195000         0.611   0.614    -8.815       0.0672   
1           1         194641         0.638   0.781    -6.848       0.0285   
2           2         217573         0.560   0.810    -8.029       0.0872   
3           3         443478         0.525   0.699    -4.571       0.0353   
4           4         225862         0.367   0.771    -5.863       0.1060   

   acousticness  instrumentalness  liveness  valence    tempo     spec_rate  \
0        0.0169          0.000794    0.7530    0.520  128.050  3.450000e-07   
1        0.0118          0.009530    0.3490    0.250  122.985  1.460000e-07   
2        0.0071          0.000008    0.2410    0.247  170.044  4.010000e-07   
3        0.0178          0.000088    0.0888    0.199   92.011  7.960000e-08   
4        0.3650          0.000001    0.0965    0.163  115.917  4.690000e-07   

   labels  
0       2  
1       1  
2       1  
3       0  
4       1

In [62]:
imp_data = song_df.drop(['Unnamed: 0','duration (ms)', 'instrumentalness','spec_rate','speechiness','loudness','valence'],axis = 1)

In [63]:
imp_data.head()

danceability  energy  acousticness  liveness    tempo  labels
0         0.611   0.614        0.0169    0.7530  128.050       2
1         0.638   0.781        0.0118    0.3490  122.985       1
2         0.560   0.810        0.0071    0.2410  170.044       1
3         0.525   0.699        0.0178    0.0888   92.011       0
4         0.367   0.771        0.3650    0.0965  115.917       1

In [64]:
x = imp_data.iloc[:,:-1]
y = imp_data.iloc[:,-1]

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [67]:
model = LogisticRegression()

In [68]:
model.fit(x_train,y_train)

c:\Users\paawan\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [69]:
y_pred = model.predict(x_test)

In [70]:
classification_report(y_pred,y_test)

'              precision    recall  f1-score   support\n\n           0       0.65      0.67      0.66     15902\n           1       0.84      0.78      0.81     22960\n           2       0.77      0.76      0.77      9572\n           3       0.57      0.67      0.61      7154\n\n    accuracy                           0.73     55588\n   macro avg       0.71      0.72      0.71     55588\nweighted avg       0.74      0.73      0.73     55588\n'

In [71]:
(accuracy_score(y_pred,y_test)*100).round(3)

72.922

In [72]:
from sklearn.neighbors import KNeighborsClassifier

In [73]:
knn_model = KNeighborsClassifier(n_neighbors= 4)


In [74]:
knn_model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [75]:
y_pred_knn = knn_model.predict(x_test)

In [76]:
(accuracy_score(y_pred_knn,y_pred)*100).round(3)

77.752

In [77]:
import pickle

In [78]:
pickle.dump(knn_model,open('knn_model.pkl','wb'))

In [79]:
pickle.dump(model,open('lr_model.pkl','wb'))

In [80]:
x_train.head()

danceability  energy  acousticness  liveness    tempo
109671         0.226   0.197      0.561000    0.0932   72.954
59603          0.530   0.993      0.000052    0.2770  170.076
259633         0.898   0.560      0.002380    0.1080  146.458
233712         0.811   0.684      0.584000    0.2690  100.017
1116           0.729   0.792      0.194000    0.0795  129.985

In [81]:
x_test.head()

danceability  energy  acousticness  liveness    tempo
45338          0.576  0.8620      0.878000     0.796  115.815
203431         0.442  0.4500      0.009800     0.111  119.987
212958         0.416  0.6670      0.000143     0.304  182.025
262553         0.143  0.0532      0.901000     0.157  140.450
19720          0.810  0.7210      0.231000     0.324  103.006

In [82]:
y_test

45338     1
203431    3
212958    2
262553    3
19720     1
         ..
187845    1
203944    3
66777     0
207571    1
106943    3
Name: labels, Length: 55588, dtype: int64

In [90]:
myarr = np.array([0.1,0.6,1.2,0.5,111.2])
myarr.reshape(1,5)


array([[1.000e-01, 6.000e-01, 1.200e+00, 5.000e-01, 1.112e+02]])

In [84]:
x_test.shape

(55588, 5)

In [91]:
df = pd.DataFrame([myarr],columns=['danceability','energy','acousticness','liveness','tempo'])

In [92]:
df

danceability  energy  acousticness  liveness  tempo
0           0.1     0.6           1.2       0.5  111.2

In [93]:
model.predict(df)

array([3], dtype=int64)

In [95]:
feature = np.array([1,2,3,4,5])

In [97]:
feature.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [98]:
feature

array([1, 2, 3, 4, 5])

In [100]:
y_pred.shape

(55588,)